### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by exoego** [balshor/aws-sdk-scalajs-facade#1]
Hello,

I am looking forward to use and/or modify this project for my AWS development project.
If I can, under what licenses can I use this project?

**Comment by balshor** [comment]
Let's go with Apache 2.0 since that's the same license as the ask-sdk-js.  I'll update the relevant projects with License files.

**Comment by balshor** [comment]
License files added to both aws-sdk-scalajs-facade and aws-sdk-apis-parser projects.

**Comment by exoego** [comment]
I appreciate for quick response!
Apache 2.0 license is fine for me.
